workdir: "/path/to/output/directory"
# set to a local cp installation if you need extra dependencies
# if unset, will use cellprofiler 4.2.6
cp_env: "cellprofiler"
# set to plugin directory
# if unset, will not include additional plugins
cp_plugin_dir: "/path/to/cellprofiler_plugins/"

paths:
  config: "logs/config_{date}.yaml"
  slurm_output: "logs/slurm"

  batch_inputs: "{pipeline}/{image_set}/inputs/batch_{batch}.txt"
  batch_outputs: "{pipeline}/{image_set}/temp_outputs/batch_{batch}"
  final_outputs: "{pipeline}/{image_set}/outputs"

pipelines:
  defaults:
    max_batch_size: 0.75  # total image size for batches, in GB
    # resources for cluster integration
    runtime: 63  # in minutes, keep >= 63
    mem_mb: 24000  # in MB
    continue_on_error: False  # if true, will skip images with errors
    recursive_images: False  # if true, include images in all subdirectories

  morphology:  # name replaces {pipeline} above
    pipeline_file: /path/to/pipeline.cppipe
    max_batch_size: 1  # can overwrite defaults at the pipeline level
    input_images:
      CX:  # name replaces {image_set} above
        runtime: 120  # can overwrite defaults at the sample level
        continue_on_error: True
        files: /path/to/images/{sample}.nd2
      Fib:  # use the same pipeline for multiple files
        files: /path/to/more_images/{sample}Denoised.nd2
        #                                   ^only match files ending in Denoised
        # {sample} is only a placeholder
